server:
  port : 8082
  servlet: 
    context-path: /
    session:
      timeout : 3600
spring:
  profiles: 
    active: dev 
Globals:
  OsType : WINDOWS
  LocalIp : 127.0.0.1
  DbType : mysql
  mysql:
    DriverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    Url : jdbc:log4jdbc:mysql://59.14.245.89:20001/DB_DISPLAYINFO?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC&allowMultiQueries=true
    UserName : root
    Password : Qwer1234!@#$
  fileUpload:
    Extensions: .gif.jpg.jpeg.png.xls.xlsx
  filePath : C:\\dev\\eGovFrameDev-4.1.0-64bit\\workspace\\IPCC\\IPCC\\backend_mo\\src\\main\\webapp\\upload
  editorPath : C:\\dev\\eGovFrameDev-4.1.0-64bit\\workspace\\IPCC\\IPCC\\backend_mo\\src\\main\\webapp\\upload\\editor
  Allow:
    Origin: "http://localhost:8080"
  crypto:
    algoritm : egovframe
springdoc:
  packages-to-scan: com.colabear754.springdoc_example.controllers
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
token:
  expiration_time : 6000000
  refresh_time : 86400000 #24*60*60*1000
  secret : Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4HQ4NSl604sgyHJj1qwEkR3ycUeR4uUAt7W